"""
SQLite persistent memory for Layla — re-exports domain modules.

Tables and behavior unchanged; see layla/memory/migrations.py for schema.
"""
from layla.memory.db_connection import _DB_PATH, _conn
from layla.memory.migrations import _MIGRATED, migrate

from layla.memory.learnings import (
    save_learning,
    _ASPECT_LEARNING_PREFERENCE,
    count_learnings,
    get_recent_learnings,
    _apply_confidence_decay,
    search_learnings_fts,
    get_learnings_by_embedding_ids,
    delete_learnings_by_id,
    get_learnings_due_for_review,
    schedule_next_review,
    set_learning_importance,
)

from layla.memory.plans_db import (
    save_study_plan,
    get_active_study_plans,
    get_plan_by_topic,
    update_study_progress,
    _VALID_PLAN_STATUSES,
    create_layla_plan,
    get_layla_plan,
    update_layla_plan,
    list_layla_plans,
    approve_layla_plan,
    set_layla_plan_status,
    normalize_workspace_root,
    save_repo_cognition_snapshot,
    get_repo_cognition_snapshot,
    list_repo_cognition_snapshots,
)

from layla.memory.audit_session import (
    log_wakeup,
    get_last_wakeup,
    log_audit,
    get_recent_audit,
    save_session_prompt,
    get_recent_session_prompts,
    add_tool_permission_grant,
    tool_grant_matches,
)

from layla.memory.conversations import (
    add_conversation_summary,
    get_recent_conversation_summaries,
    _auto_name_conversation,
    create_conversation,
    get_conversation,
    list_conversations,
    rename_conversation,
    delete_conversation,
    append_conversation_message,
    get_conversation_messages,
    search_conversations,
)

from layla.memory.projects_db import (
    create_project,
    list_projects,
    get_project,
    update_project,
    delete_project,
    set_conversation_project,
    get_project_context,
    PROJECT_LIFECYCLE_STAGES,
    set_project_context,
)

from layla.memory.user_profile import (
    add_relationship_memory,
    get_recent_relationship_memories,
    TIMELINE_EVENT_TYPES,
    add_timeline_event,
    get_recent_timeline_events,
    USER_IDENTITY_KEYS,
    get_user_identity,
    get_all_user_identity,
    set_user_identity,
    create_episode,
    add_episode_event,
    get_recent_episodes,
    record_tool_outcome,
    get_tool_reliability,
    add_goal,
    add_goal_progress,
    get_active_goals,
    save_aspect_memory,
    get_aspect_memories,
    save_earned_title,
    get_earned_title,
)

from layla.memory.capabilities_db import (
    get_capability_domains,
    get_capabilities,
    get_capability,
    insert_capability_event,
    update_capability,
    get_recent_capability_events,
    get_scheduler_history,
    append_scheduler_history,
    get_capability_dependencies,
    get_capability_implementation,
    upsert_capability_implementation,
    get_best_capability_implementation,
    list_capability_implementations,
    get_style_profile,
    set_style_profile,
)

from layla.memory.missions_db import (
    create_mission_chain,
    get_pending_mission_chains,
    complete_mission_chain,
    save_mission,
    get_mission,
    update_mission_status,
    update_mission_progress,
    get_active_missions,
    get_missions,
    save_background_task,
    update_background_task,
    get_background_task,
    list_background_tasks,
)

from layla.memory.telemetry_db import (
    log_telemetry_event,
    get_recent_telemetry_events,
)

__all__ = [
    '_DB_PATH',
    '_MIGRATED',
    '_conn',
    'migrate',
    'save_learning',
    '_ASPECT_LEARNING_PREFERENCE',
    'count_learnings',
    'get_recent_learnings',
    '_apply_confidence_decay',
    'search_learnings_fts',
    'get_learnings_by_embedding_ids',
    'delete_learnings_by_id',
    'get_learnings_due_for_review',
    'schedule_next_review',
    'set_learning_importance',
    'save_study_plan',
    'get_active_study_plans',
    'get_plan_by_topic',
    'update_study_progress',
    '_VALID_PLAN_STATUSES',
    'create_layla_plan',
    'get_layla_plan',
    'update_layla_plan',
    'list_layla_plans',
    'approve_layla_plan',
    'set_layla_plan_status',
    'normalize_workspace_root',
    'save_repo_cognition_snapshot',
    'get_repo_cognition_snapshot',
    'list_repo_cognition_snapshots',
    'log_wakeup',
    'get_last_wakeup',
    'log_audit',
    'get_recent_audit',
    'save_session_prompt',
    'get_recent_session_prompts',
    'add_tool_permission_grant',
    'tool_grant_matches',
    'add_conversation_summary',
    'get_recent_conversation_summaries',
    '_auto_name_conversation',
    'create_conversation',
    'get_conversation',
    'list_conversations',
    'rename_conversation',
    'delete_conversation',
    'append_conversation_message',
    'get_conversation_messages',
    'search_conversations',
    'create_project',
    'list_projects',
    'get_project',
    'update_project',
    'delete_project',
    'set_conversation_project',
    'get_project_context',
    'PROJECT_LIFECYCLE_STAGES',
    'set_project_context',
    'add_relationship_memory',
    'get_recent_relationship_memories',
    'TIMELINE_EVENT_TYPES',
    'add_timeline_event',
    'get_recent_timeline_events',
    'USER_IDENTITY_KEYS',
    'get_user_identity',
    'get_all_user_identity',
    'set_user_identity',
    'create_episode',
    'add_episode_event',
    'get_recent_episodes',
    'record_tool_outcome',
    'get_tool_reliability',
    'add_goal',
    'add_goal_progress',
    'get_active_goals',
    'save_aspect_memory',
    'get_aspect_memories',
    'save_earned_title',
    'get_earned_title',
    'get_capability_domains',
    'get_capabilities',
    'get_capability',
    'insert_capability_event',
    'update_capability',
    'get_recent_capability_events',
    'get_scheduler_history',
    'append_scheduler_history',
    'get_capability_dependencies',
    'get_capability_implementation',
    'upsert_capability_implementation',
    'get_best_capability_implementation',
    'list_capability_implementations',
    'get_style_profile',
    'set_style_profile',
    'create_mission_chain',
    'get_pending_mission_chains',
    'complete_mission_chain',
    'save_mission',
    'get_mission',
    'update_mission_status',
    'update_mission_progress',
    'get_active_missions',
    'get_missions',
    'save_background_task',
    'update_background_task',
    'get_background_task',
    'list_background_tasks',
    'log_telemetry_event',
    'get_recent_telemetry_events',
]

