"""File system and document tools."""

TOOLS = {
    "write_file": {"dangerous": True, "require_approval": True, "risk_level": "medium"},
    "write_files_batch": {"dangerous": True, "require_approval": True, "risk_level": "high"},
    "read_file": {"dangerous": False, "require_approval": False, "risk_level": "low", "concurrency_safe": True},
    "list_dir": {"dangerous": False, "require_approval": False, "risk_level": "low", "concurrency_safe": True},
    "tail_file": {"dangerous": False, "require_approval": False, "risk_level": "low", "concurrency_safe": True},
    "file_info": {"dangerous": False, "require_approval": False, "risk_level": "low", "concurrency_safe": True},
    "glob_files": {"dangerous": False, "require_approval": False, "risk_level": "low", "concurrency_safe": True},
    "diff_files": {"dangerous": False, "require_approval": False, "risk_level": "low", "concurrency_safe": True},
    "parse_gcode": {"dangerous": False, "require_approval": False, "risk_level": "low"},
    "stl_mesh_info": {"dangerous": False, "require_approval": False, "risk_level": "low"},
    "clipboard_read": {"dangerous": False, "require_approval": False, "risk_level": "low"},
    "clipboard_write": {"dangerous": False, "require_approval": True, "risk_level": "medium"},
    "search_replace": {"dangerous": True, "require_approval": True, "risk_level": "medium"},
    "replace_in_file": {"dangerous": True, "require_approval": True, "risk_level": "medium"},
    "apply_patch": {"dangerous": True, "require_approval": True, "risk_level": "medium"},
    "json_query": {"dangerous": False, "require_approval": False, "risk_level": "low", "concurrency_safe": True},
    "understand_file": {"fn_key": "understand_file_tool", "dangerous": False, "require_approval": False, "risk_level": "low"},
    "workspace_map": {"dangerous": False, "require_approval": False, "risk_level": "low", "concurrency_safe": True},
    "sync_repo_cognition": {"dangerous": False, "require_approval": False, "risk_level": "low", "concurrency_safe": True},
    "scan_repo": {"dangerous": True, "require_approval": True, "risk_level": "medium"},
    "update_project_memory": {"dangerous": True, "require_approval": True, "risk_level": "medium"},
    "read_pdf": {"dangerous": False, "require_approval": False, "risk_level": "low"},
    "read_docx": {"dangerous": False, "require_approval": False, "risk_level": "low"},
    "read_excel": {"dangerous": False, "require_approval": False, "risk_level": "low"},
    "hash_file": {"dangerous": False, "require_approval": False, "risk_level": "low"},
    "yaml_read": {"dangerous": False, "require_approval": False, "risk_level": "low"},
    "xml_parse": {"dangerous": False, "require_approval": False, "risk_level": "low"},
    "read_toml": {"dangerous": False, "require_approval": False, "risk_level": "low"},
    "merge_pdf": {"dangerous": False, "require_approval": False, "risk_level": "low"},
    "write_csv": {"dangerous": True, "require_approval": True, "risk_level": "medium"},
    "extract_archive": {"dangerous": False, "require_approval": False, "risk_level": "low"},
    "create_archive": {"dangerous": False, "require_approval": False, "risk_level": "low"},
    "base64_tool": {"dangerous": False, "require_approval": False, "risk_level": "low"},
    "list_file_checkpoints": {"dangerous": False, "require_approval": False, "risk_level": "low", "concurrency_safe": True},
    "restore_file_checkpoint": {"dangerous": True, "require_approval": True, "risk_level": "medium"},
}
