"""General context, goals, utilities, and meta tools."""

TOOLS = {
    "get_project_context": {"fn_key": "get_project_context_tool", "dangerous": False, "require_approval": False, "risk_level": "low"},
    "update_project_context": {"fn_key": "update_project_context_tool", "dangerous": False, "require_approval": False, "risk_level": "low"},
    "get_user_identity": {"fn_key": "get_user_identity_tool", "dangerous": False, "require_approval": False, "risk_level": "low"},
    "update_user_identity": {"fn_key": "update_user_identity_tool", "dangerous": False, "require_approval": False, "risk_level": "low"},
    "add_goal": {"fn_key": "add_goal_tool", "dangerous": False, "require_approval": False, "risk_level": "low"},
    "add_goal_progress": {"fn_key": "add_goal_progress_tool", "dangerous": False, "require_approval": False, "risk_level": "low"},
    "get_active_goals": {"fn_key": "get_active_goals_tool", "dangerous": False, "require_approval": False, "risk_level": "low"},
    "list_tools": {"dangerous": False, "require_approval": False, "risk_level": "low"},
    "tool_recommend": {"dangerous": False, "require_approval": False, "risk_level": "low"},
    "image_resize": {"dangerous": False, "require_approval": False, "risk_level": "low"},
    "extract_frames": {"dangerous": False, "require_approval": False, "risk_level": "medium"},
    "detect_scenes": {"dangerous": False, "require_approval": False, "risk_level": "low"},
    "detect_objects": {"dangerous": False, "require_approval": False, "risk_level": "low"},
    "geo_query": {"dangerous": False, "require_approval": False, "risk_level": "low"},
    "map_url": {"dangerous": False, "require_approval": False, "risk_level": "low"},
    "uuid_generate": {"dangerous": False, "require_approval": False, "risk_level": "low"},
    "random_string": {"dangerous": False, "require_approval": False, "risk_level": "low"},
    "password_generate": {"dangerous": False, "require_approval": False, "risk_level": "low"},
    "string_transform": {"dangerous": False, "require_approval": False, "risk_level": "low"},
    "timestamp_convert": {"dangerous": False, "require_approval": False, "risk_level": "low"},
    "generate_qr": {"dangerous": False, "require_approval": False, "risk_level": "low"},
    "json_schema": {"dangerous": False, "require_approval": False, "risk_level": "low"},
    "jwt_decode": {"dangerous": False, "require_approval": False, "risk_level": "low"},
    "create_svg": {"dangerous": True, "require_approval": True, "risk_level": "medium"},
    "create_mermaid": {"dangerous": True, "require_approval": True, "risk_level": "medium"},
    "log_event": {"dangerous": False, "require_approval": False, "risk_level": "low"},
    "trace_last_run": {"dangerous": False, "require_approval": False, "risk_level": "low"},
    "tool_metrics": {"dangerous": False, "require_approval": False, "risk_level": "low"},
    "stt_file": {"dangerous": False, "require_approval": False, "risk_level": "low"},
    "tts_speak": {"dangerous": False, "require_approval": False, "risk_level": "low"},
    "crypto_prices": {"dangerous": False, "require_approval": False, "risk_level": "low"},
    "economic_indicators": {"dangerous": False, "require_approval": False, "risk_level": "low"},
    "structured_llm_task": {"fn_key": "structured_llm_task", "dangerous": False, "require_approval": False, "risk_level": "low"},
    "mcp_tools_call": {"fn_key": "mcp_tools_call", "dangerous": True, "require_approval": True, "risk_level": "high"},
    "mcp_list_mcp_tools": {"fn_key": "mcp_list_mcp_tools", "dangerous": False, "require_approval": False, "risk_level": "low"},
    "mcp_list_mcp_resources": {"fn_key": "mcp_list_mcp_resources", "dangerous": False, "require_approval": False, "risk_level": "low"},
    "mcp_read_mcp_resource": {"fn_key": "mcp_read_mcp_resource", "dangerous": False, "require_approval": False, "risk_level": "low"},
    "mcp_operator_auth_hint": {"fn_key": "mcp_operator_auth_hint", "dangerous": False, "require_approval": False, "risk_level": "low"},
    "notebook_read_cells": {"fn_key": "notebook_read_cells", "dangerous": False, "require_approval": False, "risk_level": "low"},
    "notebook_edit_cell": {"fn_key": "notebook_edit_cell", "dangerous": True, "require_approval": True, "risk_level": "medium"},
}
