"""Ollama-native API surface (UPG-41 / BL-152).

Lets any tool that speaks Ollama's HTTP API (Open WebUI, ollama-python, editor plugins, …)
point straight at Layla. We translate Ollama's `/api/chat` + `/api/generate` into the existing
OpenAI-compatible handler (so all of the agent logic, aspect routing, and the local-only
write/run security carry over untouched), and expose `/api/tags` + `/api/version` for discovery.
An explicit ``stream: true`` gets protocol-correct NDJSON (application/x-ndjson) frames — the reply
is generated by the safe non-stream path, then chunked, so live-safety is not re-implemented; absent
or ``stream: false`` keeps the single-JSON reply for backward compatibility.
"""
from __future__ import annotations

import json
import time
import uuid

from fastapi import APIRouter, Request
from fastapi.responses import JSONResponse, StreamingResponse

router = APIRouter(tags=["ollama"])


def _now() -> str:
    return time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())


def _aspect_ids() -> list[str]:
    try:
        from services.personality.character_creator import all_aspect_ids
        return list(all_aspect_ids())
    except Exception:
        return ["morrigan", "nyx", "echo", "eris", "cassandra", "lilith"]


def _json_of(resp) -> dict:
    """Extract the JSON dict from a JSONResponse (or a plain dict)."""
    if isinstance(resp, JSONResponse):
        try:
            return json.loads(resp.body)
        except Exception:
            return {}
    return resp if isinstance(resp, dict) else {}


def _content_of(resp) -> tuple[str, dict]:
    d = _json_of(resp)
    content = ((d.get("choices") or [{}])[0].get("message") or {}).get("content", "") or ""
    return content, d


def _map_ollama_options(body: dict, oai: dict) -> None:
    """Plan #18: Ollama nests sampling under ``options``; map it onto the OpenAI body so the
    v1 handler's ``_extract_sampling`` clamps it and threads it to the FINAL generation. Only
    keys the client actually set are forwarded (so absence stays absence → no override). Ollama's
    ``num_predict`` is the max-tokens equivalent; ``stop`` is forwarded verbatim (v1 coerces it).
    """
    opts = (body or {}).get("options") or {}
    if not isinstance(opts, dict):
        return
    for src, dst in (
        ("temperature", "temperature"),
        ("top_p", "top_p"),
        ("top_k", "top_k"),
        ("seed", "seed"),
        ("num_predict", "max_tokens"),
        ("stop", "stop"),
    ):
        if opts.get(src) is not None:
            oai[dst] = opts.get(src)


async def _ollama_content(oai: dict, request: Request) -> tuple[str, dict, str | None]:
    """Run the SAFE non-stream v1 path and return (content, data, error_message|None)."""
    from routers.openai_compat import v1_chat_completions

    resp = await v1_chat_completions(oai, request)
    content, d = _content_of(resp)
    err = None
    if not d.get("choices") and d.get("error"):
        err = (d.get("error") or {}).get("message", "error")
    return content, d, err


def _ndjson_frames(model: str, content: str, *, generate: bool):
    """Yield Ollama NDJSON frames for an already-generated (and already safety-filtered) reply.

    The content is produced up-front by the non-stream path, then chunked here — protocol-correct
    for streaming clients (Content-Type application/x-ndjson) without re-running the live-safety
    machinery. `generate` selects the /api/generate ('response') vs /api/chat ('message') shape.
    """
    created = _now()
    step = 48  # chars per frame — incremental render without a frame per byte
    for i in range(0, len(content), step):
        ch = content[i:i + step]
        if generate:
            frame = {"model": model, "created_at": created, "response": ch, "done": False}
        else:
            frame = {"model": model, "created_at": created,
                     "message": {"role": "assistant", "content": ch}, "done": False}
        yield json.dumps(frame, ensure_ascii=False) + "\n"
    if generate:
        done = {"model": model, "created_at": _now(), "response": "", "done": True, "done_reason": "stop"}
    else:
        done = {"model": model, "created_at": _now(),
                "message": {"role": "assistant", "content": ""}, "done": True, "done_reason": "stop"}
    yield json.dumps(done, ensure_ascii=False) + "\n"


@router.get("/api/version")
def ollama_version():
    return {"version": "0.1.0-layla"}


@router.get("/api/tags")
def ollama_tags():
    """List Layla's 'models' (the base model + each aspect) in Ollama's tag shape."""
    names = ["layla"] + [f"layla-{a}" for a in _aspect_ids()]
    models = [
        {
            "name": n,
            "model": n,
            "modified_at": _now(),
            "size": 0,
            "digest": "",
            "details": {"family": "layla", "format": "gguf", "parameter_size": "", "quantization_level": ""},
        }
        for n in names
    ]
    return {"models": models}


@router.post("/api/chat")
async def ollama_chat(req: dict, request: Request):
    """Ollama /api/chat → OpenAI /v1/chat/completions → Ollama response."""
    from routers.openai_compat import v1_chat_completions

    body = req or {}
    oai = {
        "model": str(body.get("model") or "layla"),
        "messages": body.get("messages") or [],
        "stream": False,
        "workspace_root": body.get("workspace_root", "") or (body.get("options") or {}).get("workspace_root", ""),
    }
    _map_ollama_options(body, oai)   # plan #18: forward temp/top_p/top_k/seed/num_predict + stop to v1
    model = body.get("model") or "layla"
    content, d, err = await _ollama_content(oai, request)
    if err:
        if body.get("stream") is True:
            return StreamingResponse(iter([json.dumps({"error": err}) + "\n"]),
                                     media_type="application/x-ndjson", status_code=400)
        return JSONResponse({"error": err}, status_code=400)
    # Honor an EXPLICIT stream:true with protocol-correct NDJSON (Ollama's default is streaming, and
    # real clients — Open WebUI, ollama-python — parse NDJSON). Absent/false keeps the single-JSON
    # reply for backward compatibility.
    if body.get("stream") is True:
        return StreamingResponse(_ndjson_frames(model, content, generate=False),
                                 media_type="application/x-ndjson")
    return {
        "model": model,
        "created_at": _now(),
        "message": {"role": "assistant", "content": content},
        "done": True,
        "done_reason": "stop",
    }


@router.post("/api/generate")
async def ollama_generate(req: dict, request: Request):
    """Ollama /api/generate (prompt string) → OpenAI chat → Ollama response."""
    from routers.openai_compat import v1_chat_completions

    body = req or {}
    prompt = str(body.get("prompt") or "")
    oai = {
        "model": str(body.get("model") or "layla"),
        "messages": [{"role": "user", "content": prompt}],
        "stream": False,
        "workspace_root": body.get("workspace_root", "") or (body.get("options") or {}).get("workspace_root", ""),
    }
    _map_ollama_options(body, oai)   # plan #18: forward temp/top_p/top_k/seed/num_predict + stop to v1
    model = body.get("model") or "layla"
    content, d, err = await _ollama_content(oai, request)
    if err:
        if body.get("stream") is True:
            return StreamingResponse(iter([json.dumps({"error": err}) + "\n"]),
                                     media_type="application/x-ndjson", status_code=400)
        return JSONResponse({"error": err}, status_code=400)
    if body.get("stream") is True:
        return StreamingResponse(_ndjson_frames(model, content, generate=True),
                                 media_type="application/x-ndjson")
    return {
        "model": model,
        "created_at": _now(),
        "response": content,
        "done": True,
        "done_reason": "stop",
    }
